name       : mate-themes
version    : 3.22.19
release    : 12
source     :
    - https://github.com/mate-desktop/mate-themes/archive/v3.22.19.tar.gz : 5015e2b703095113d3f53c977a6d09d22a17b3e14d9c923e2936df78ed39afa8
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Desktop themes
description: |
    Themes for the MATE Desktop
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - mate-common
rundeps    :
    - gnome-icon-theme
    - mate-icon-theme
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
