name       : mate-themes
version    : 3.22.14
release    : 9
source     :
    - http://pub.mate-desktop.org/releases/themes/3.22/mate-themes-3.22.14.tar.xz : 53b59fdc40fd5c35b85119231cd8e1d490d8e7f369cb43b31a87ed5c2dddd825
license    : LGPL-2.0
component  : desktop.mate
summary    : Themes for the MATE Desktop
description: |
    Themes for the MATE Desktop
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
rundeps    :
    - gnome-icon-theme
    - mate-icon-theme
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
