name       : mate-themes
version    : 3.20.10
release    : 1
source     :
    - http://pub.mate-desktop.org/releases/themes/3.20/mate-themes-3.20.10.tar.xz : 91c114fcb14979d88dae76a7e2e3b37f439f5daf0dd8a492c17a6174638b102e
license    : LGPL-2.0
component  : desktop.mate
summary    : Themes for the MATE Desktop
description: |
    Themes for the MATE Desktop
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
