name       : mate-themes
version    : 3.22.22
release    : 15
source     :
    - https://github.com/mate-desktop/mate-themes/releases/download/v3.22.22/mate-themes-3.22.22.tar.xz : bd00affe5aec217656c0af21496a4c66fd5f6f3e9e93b42fc96b54771d6f99a1
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Desktop themes
description: |
    Themes for the MATE Desktop
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
rundeps    :
    - gnome-icon-theme
    - mate-icon-theme
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
