name       : mate-themes
version    : 3.22.23
release    : 16
source     :
    - https://github.com/mate-desktop/mate-themes/releases/download/v3.22.23/mate-themes-3.22.23.tar.xz : 61e5ad626c9841f5763c908f1769139b2a812687b98f6b330afee4da18fb6fab
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Desktop themes
description: |
    Themes for the MATE Desktop
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
rundeps    :
    - gnome-icon-theme
    - mate-icon-theme
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
