name       : mate-themes
version    : 3.22.20
release    : 13
source     :
    - https://github.com/mate-desktop/mate-themes/archive/v3.22.20.tar.gz : b9442fc45fdc665bbb257b22c1435470c261a551a34e81942876fdd97e9d6330
license    : LGPL-2.1-or-later
component  : desktop.mate
summary    : MATE Desktop themes
description: |
    Themes for the MATE Desktop
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - mate-common
rundeps    :
    - gnome-icon-theme
    - mate-icon-theme
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
