name       : mate-themes
version    : 3.22.8
release    : 5
source     :
    - http://pub.mate-desktop.org/releases/themes/3.22/mate-themes-3.22.8.tar.xz : c312684500afe066f34f250530a08ba6c2c52881f398a2fbde8586f89feb9b3f
license    : LGPL-2.0
component  : desktop.mate
summary    : Themes for the MATE Desktop
description: |
    Themes for the MATE Desktop
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
