name       : mate-themes
version    : 3.22.15
release    : 10
source     :
    - http://pub.mate-desktop.org/releases/themes/3.22/mate-themes-3.22.15.tar.xz : 8f9bbdf3103a5843f06c61afec935c2154e02b7fdaf6c2726c5b4dba8d5cb432
license    : LGPL-2.0
component  : desktop.mate
summary    : Themes for the MATE Desktop
description: |
    Themes for the MATE Desktop
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
rundeps    :
    - gnome-icon-theme
    - mate-icon-theme
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
